name: Build
on:
  push:
    branches: [ next.js ]
  pull_request:
    branches: [ next.js ]
jobs:
  build:
    name: Build page and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      uses: bahmutov/npm-install@HEAD
    - name: Build page
      run: yarn build
    - name: Test
      run: yarn test
